OpenCV   
!pip install tensorflow   
!pip install opencv-python   
https://docs.opencv.org/4.x/d0/de3/tutorial_py_intro.html

In [2]:
from tensorflow.keras.datasets import mnist
import cv2
import matplotlib.pyplot as plt

In [3]:
cv2.__version__

'4.10.0'

In [4]:
mnist.load_data?

Signature: mnist.load_data(path='mnist.npz')
Docstring:
Loads the MNIST dataset.

This is a dataset of 60,000 28x28 grayscale images of the 10 digits,
along with a test set of 10,000 images.
More info can be found at the
[MNIST homepage](http://yann.lecun.com/exdb/mnist/).

Args:
    path: path where to cache the dataset locally
        (relative to `~/.keras/datasets`).

Returns:
    Tuple of NumPy arrays: `(x_train, y_train), (x_test, y_test)`.

**`x_train`**: `uint8` NumPy array of grayscale image data with shapes
  `(60000, 28, 28)`, containing the training data. Pixel values range
  from 0 to 255.

**`y_train`**: `uint8` NumPy array of digit labels (integers in range 0-9)
  with shape `(60000,)` for the training data.

**`x_test`**: `uint8` NumPy array of grayscale image data with shapes
  `(10000, 28, 28)`, containing the test data. Pixel values range
  from 0 to 255.

**`y_test`**: `uint8` NumPy array of digit labels (integers in range 0-9)
  with shape `(10000,)` for the test d

In [5]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [6]:
type(X_train), X_train.dtype, X_train.ndim, X_train.shape, X_train.size

(numpy.ndarray, dtype('uint8'), 3, (60000, 28, 28), 47040000)

In [7]:
X_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [8]:
y_train[0]

5

In [9]:
# 자동 제한없이 행렬 전체 출력
import sys
import numpy as np
# np.set_printoptions(threshold=np.inf, linewidth=np.inf) # 컴퓨터 성능에 영향을 줄 수 있으므로 주의 할 것
np.set_printoptions(linewidth = 150, precision = 2)

In [10]:
X_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,  18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 154, 170, 253, 253, 253, 253, 253, 225, 172

In [11]:
X_train[1]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  51, 159, 253, 159,  50,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  48, 238, 252, 252, 252, 237,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  54, 227, 253, 252, 239, 233, 252

## 이미지 읽고 출력
pixabay 무료 이미지 소스 가져오기

In [13]:
from google.colab import drive
drive.mount('/content/drive')

ModuleNotFoundError: No module named 'google.colab'

In [ ]:
pwd

In [ ]:
from tensorflow.keras.datasets import mnist
import cv2
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# 이미지 읽어오기
img = cv2.imread('/content/drive/MyDrive/Lecture/ESTsoft/WASSUP2기_교안/03_Data_Preprocessing/data/car.jpg')  # BGR로 인식하므로 컨버팅 필요

In [ ]:
img

In [ ]:
img = cv2.imread('/content/car.jpg')
img

In [ ]:
cv2.imread?

In [ ]:
image = img

In [ ]:
type(image), image.dtype, image.ndim, image.shape, image.size

In [ ]:
image[0]

In [ ]:
plt.imshow(image)

In [ ]:
# # 이미지 출력
# cv2.imshow('title', image) # 원본 출력
# cv2.waitKey(0)
# cv2.destroyAllWindows()

## 컨버팅
### 왜 OpenCV는 BGR을 쓸까?
일반적인 방법인 PIL로 이미지를 읽으면 RGB 순서로, OpenCV로 읽으면(cv2.imread 등) BGR순서로 이미지가 읽힌다.   
RGB, BGR 각각 Color space 또는 Color system을 말하며, 유추할 수 있듯 색상이 저장되는 순서가 서로 정반대이다.   
https://blog.xcoda.net/102   
https://learnopencv.com/why-does-opencv-use-bgr-color-format/

In [ ]:
def imginfo(image):
    print(type(image), image.dtype, image.ndim, image.shape, image.size)

In [ ]:
# bgr => rgb
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB) # RGB로 컨버팅
plt.imshow(image)
# plt.show()# 객체 디스크립션 숨김
imginfo(image)

In [ ]:
# bgr => gray
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
plt.imshow(gray) # cmap ='gray'
imginfo(gray)

In [ ]:
gray[0], imginfo(gray[0])

In [ ]:
# gray => colormap
im_color = cv2.applyColorMap(gray, cv2.COLORMAP_SUMMER)
plt.imshow(im_color)
imginfo(im_color)

In [ ]:
hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
plt.imshow(hsv)
imginfo(hsv)

lower_green = np.array([0, 100, 0])   

upper_green = np.array([100, 200, 100])
![image-2.png](attachment:image-2.png)

In [ ]:
# 그린 색상 마스킹 = 크로마키
lower_green = np.array([0, 50, 0])
upper_green = np.array([100, 255, 100])

mask_green = cv2.inRange(hsv, lower_green, upper_green)
plt.imshow(mask_green)

## 크기 조절
보간법 : 이미지의 크기를 변경하는 경우, 변형된 이미지의 픽셀은 추정해서 값을 할당해야 합니다.   
이미지의 비율을 변경하면 존재하지 않는 영역에 새로운 픽셀값을 매핑하거나 존재하는 픽셀들을 압축해서 새로운 값을 할당해야 합니다.   
이를 이미지 상에 존재하는 픽셀 데이터들에 대해 근사 함수를 적용해서 새로운 픽셀 값을 구하는 것으로 이해할 수 있습니다.   
그러므로, 추정해야 하는 픽셀은 보간법을 이용하여 픽셀들의 값을 할당합니다.
* 이미지를 축소하려면 일반적으로 #INTER_AREA 보간을 사용하는 것이 가장 좋습니다.
* 이미지를 확대하면 일반적으로 #INTER_CUBIC(느림) 또는 #INTER_LINEAR를 사용하는 것이 가장 좋습니다.
![image.png](attachment:image.png)

In [ ]:
height, width, channel = image.shape
height, width, channel

In [ ]:
cv2.resize?

In [ ]:
# 크기 조절
dst = cv2.resize(image, dsize=(320,187), interpolation=cv2.INTER_AREA) #interpolation 보간
imginfo(dst)
plt.imshow(dst)

In [ ]:
# 크기 조절
dst = cv2.resize(image, dsize=(0,0), fx=0.3, fy=0.7, interpolation=cv2.INTER_LINEAR) # X축기준으로 30%, Y축 기준으로 70% 크기 조절, dzie(0,0)하면 비율 적용
imginfo(dst)
plt.imshow(dst)

In [ ]:
# 확대, 축소
dst3 = cv2.pyrUp(image, dstsize=(width*2, height*2))
plt.imshow(dst3)
imginfo(dst3)
plt.show

In [ ]:
cv2.pyrDown?

In [ ]:
# 이미지 축소 메서드
dst4 = cv2.pyrDown(image)
plt.imshow(dst4)
imginfo(dst4)
plt.show()

## 자르기

![image.png](attachment:995d3a3b-98d0-409f-a578-7f49cffbffd3.png)

In [ ]:
plt.imshow(image)
imginfo(image)

In [ ]:
dst5 = image[:375, :641]
plt.imshow(dst5)

In [ ]:
# 가운데 중심점을 기준으로 50% 이미지 잘라내기
# 가운데 중심점 : height/2, width/2 , 시작위치 : height/2 – height/4    ,  끝위치: height/2 + height/4를 계산
#  image[y범위, x범위]

dst6 = image[int(height/2-height/4) : int(height/2+height/4),         # y 범위
             int(width/2-width/4)  : int(width/2+width/4)] # x범위
plt.imshow(dst6)

In [ ]:
import tensorflow as tf
# IMAGE CROP
dst14 = tf.image.crop_to_bounding_box(image, 100, 200, 300, 400) # BOX좌표
# offset_height(위에서 아래로 +100), offset_width(좌에서 우방향으로 +200), target_height(offset지점에서부터 높이+300), target_width(offset지점부터 +400)
plt.imshow(dst14)

## 이동

In [ ]:
rows, cols, channels = image.shape
image.shape

In [ ]:
cv2.warpAffine?

In [ ]:
rows, cols, channels = img.shape

m = np.float32([[1,0,200],[0,1,100]]) # [x축 True, y축 false, 이동 200 ], [x축 false, y축 True, 이동 100]

dst = cv2.warpAffine(img, m, (cols,rows))

plt.imshow(dst)

## 회전

In [ ]:
cv2.getRotationMatrix2D?

In [ ]:
# 중심점에서 30도 시계방향
M = cv2.getRotationMatrix2D((cols/2, rows/2), -30, 1)

rotate_30 = cv2.warpAffine(img, M, (cols,rows))

plt.imshow(rotate_30)

## 흐리게, 선명하게
이미지 또는 영상을 흐릿하게 만드는 원리는,   
다음과 같은 kernel를 전체 이미지에 convolution을 돌림으로써, 커널 사이즈에 맞게 픽셀 평균값을 대입하는 것입니다.   
즉, 특정 픽셀의 주변 값의 평균(또는 임의의 array 연산)값을 해당 픽셀에 넣는 것입니다.   
2D Convolution kernel의 원리는 딥러닝에서도 CNN이라는 유명 알고리즘에 사용되는 동일한 방식입니다.   
그 만큼 많이 쓰이면서도 단순한 원리입니다.
![image.png](attachment:image.png)
![image-4.png](attachment:image-4.png)
![image-5.png](attachment:image-5.png)

In [ ]:
cv2.blur?

In [ ]:
dst7 = cv2.blur(image, (20, 20)) # 값이 커질수록 더 흐려짐 , 필터의 컨벌루션
plt.imshow(dst7)

In [ ]:
# 중앙값을 키워주는 형태의 마스크를 만든 후 적용하여 특징을 강조
# sharpening ; 주변 pixel과의 차이를 극대화시켜 경계부분의 명암비를 증가시키는 작업
# 주변부의 픽셀값을 감소시킬때, 강조될 강도를 mask중앙에 지정하고  주변부의 값을 줄여 총합이 1이 되도록 mask 생성
kernel = np.array([ [-1, -1, -1], [-1, 9, -1], [-1, -1, -1]    ]) # 필터 ,
dst8 = cv2.filter2D(image, -1, kernel) #두번째 인자인 depth은 출력영상의 데이터타입으로 default는 -1로 입력과 동일한 타입으로 출력
plt.imshow(dst8)

In [ ]:
fig, ax = plt.subplots(1, 3, figsize = (20, 10))
ax[0].imshow(dst7)
ax[1].imshow(image)
ax[2].imshow(dst8)

## 대칭

In [ ]:
# 상하 대칭
dst9 = cv2.flip(image, 0)
plt.imshow(dst9)

In [ ]:
# 좌우 대칭
dst10 = cv2.flip(image, 1)
plt.imshow(dst10)

In [ ]:
import tensorflow as tf
dst15 = tf.image.flip_left_right(image)
plt.imshow(dst15)

## 경계 추출, 엣지
canny 알고리즘을 이용해서 경계를 추출합니다.    
뒤의 숫자 개는 경계점을 정하는 값으로 클수록 엣지 추출값이 적어집니다.   
앞의 숫자는 minVal로 이 수치가 적어지면 인근 엣지와 더 잘 연결됩니다.   
뒤의 숫자는 maxvVal로 이 수치가 적어지면 엣지 추출이 많아집니다.   

https://engineer-mole.tistory.com/243
![image.png](attachment:image.png)

In [ ]:
cv2.Canny?

In [ ]:
dst11 = cv2.Canny(image, 500, 500) # (src, 작아질수록 엣지가 연결이 더 잘됨 , 작아질수록 엣지추출이 많아짐)
plt.imshow(dst11)

In [ ]:
dst11 = cv2.Canny(image, 50, 500)
plt.imshow(dst11)

In [ ]:
dst11 = cv2.Canny(image, 500, 50) #    (src, 작아질수록 엣지가 연결이 더 잘됨 , 작아질수록 엣지추출이 많아짐)
plt.imshow(dst11)

In [ ]:
dst11 = cv2.Canny(image, 100, 100)
plt.imshow(dst11)

## 이미지 저장

In [ ]:
# 미변환하면 색상값이 BGR로 변경되므로 컨버팅 필요
# 변환전
cv2.imwrite('car_resize1.jpg', dst7)

In [ ]:
# 변환 후
dst7_BGR = cv2.cvtColor(dst7, cv2.COLOR_BGR2RGB)
cv2.imwrite('car_resize2.jpg', dst7_BGR)

# 연습 문제
* 다양한 처리기법을 포함한 랜덤 이미지 변환 함수를 만들어보세요.
* image폴더 안에 있는 모든 이미지에 랜덤변환함수를 적용하여 result 폴더에 저장하세요

In [ ]:
import os
print(os.getcwd())
print(os.listdir())

In [ ]:
os.chdir('/content/drive/MyDrive/Lecture/ESTsoft/WASSUP2기_교안/03_Data_Preprocessing/data')
print(os.getcwd())

In [ ]:
img_folder_list = os.listdir() # /content/drive/MyDrive/Lecture/ESTsoft/WASSUP2기_교안/03_Data_Preprocessing/data
img_folder_list

In [ ]:
import glob # 경로 가져오는 모듈
img_path = glob.glob('*.jpg') # 이미지폴더내 모든 이미지파일 경로
img_path

In [ ]:
# 파일명 잘라오기
def file_name(path):
    # name = path.split('\\')[1].split('.')[0]
    name = path.split('.')[0]
    return name

In [ ]:
for i in img_path:
    print(file_name(i))

In [ ]:
import random
def rd_change(img):
    rows, cols, channels = img.shape
    rotate = random.randint(0,360)
    x_shift = random.randint(-100,100)
    y_shift = random.randint(-100,100)

    # move
    sm = np.float32([[1,0,x_shift],[0,1,y_shift]])
    img = cv2.warpAffine(img,sm,(cols,rows))

    # rotate
    rm = cv2.getRotationMatrix2D((cols/2,rows/2),rotate,1)
    img = cv2.warpAffine(img,rm,(cols,rows))

    return img

In [ ]:
# 파일명 잘라오기
def file_name(path):
    # name = path.split('\\')[1]
    name = path.split('.')[0]
    return name

In [ ]:
# 실행 및 이미지 저장
import cv2
import numpy as np
# os.mkdir('result')

num = 0
for path in img_path:
    img = cv2.imread(path)
    rd_changed = rd_change(img)

    name = file_name(path)
    #cv2.imwrite('./result/'+name, rd_changed)
    cv2.imwrite('./result/'+name+'.jpg', rd_changed)
    num += 1
    print(num, path, '변환 저장 완료')
print('전체 이미지 변환 저장이 완료됐습니다.')